apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypriot-deployment
  labels:
    app: hypriot
    type: web
spec:
  template:
    metadata:
      name: hypriot-pod
      labels:
        app: hypriot
        blink: show
    spec:
      containers:
      - image: hypriot/rpi-busybox-httpd
        name: hypriot
        ports:
        - containerPort: 80
  replicas: 3 
  selector:
     matchLabels:
      app: hypriot

---
apiVersion: v1
kind: Service
metadata:
  name: hypriot-service
spec:
  selector:
    app: hypriot
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hypriot-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hypriot.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        backend:
          serviceName: hypriot-service
          servicePort: 8888
  tls:
  - hosts:
    - "homer.${SECRET_DOMAIN}"